myFitWeb/config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: "users/registrations" }

  resources :users

  resources :profiles, shallow: true do
    resources :goals
    resources :supplements
    resources :updates, shallow: true do
      resources :pictures
    end
    resources :workouts, shallow: true do
      resources :exercises
    end
  end

  root 'home#index'

end

myFitWeb/app/models/update.rb
class Update < ActiveRecord::Base

  belongs_to :profile
  has_many :pictures


end

myFitWeb/app/controllers/updates_controller.rb
class UpdatesController < ApplicationController
  before_action :set_update, only: [:show, :edit, :update, :destroy]

  #def create_update
  #  @profile = Profile.find params[:profile_id]
  #  new_update = @profile.updates.create(weight: 0, notes: "test")

  #end

  # GET /updates
  # GET /updates.json
  def index
    @profile = Profile.find params[:profile_id]
    @workouts = @profile.workouts
    @updates = @profile.updates
  end

  # GET /updates/1
  # GET /updates/1.json
  def show
    @update = Update.find params[:id]
    @profile = @update.profile
    @picture = @update.pictures.new
  end

  # GET /updates/new
  def new
    @profile = Profile.find params[:profile_id]

    @update = @profile.updates.new
    #@picture = @update.pictures.new
  end

  # GET /updates/1/edit
  def edit
  end

  # POST /updates
  # POST /updates.json
  def create
    @profile = Profile.find params[:profile_id]
    @update = @profile.updates.new(update_params)

    respond_to do |format|
      if @update.save
        format.html { redirect_to update_path(@update), notice: 'Update was successfully created.' }
        format.json { render :show, status: :created, location: @update }
      else
        format.html { render :new }
        format.json { render json: @update.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /updates/1
  # PATCH/PUT /updates/1.json
  def update
    respond_to do |format|
      if @update.update(update_params)
        format.html { redirect_to profile_updates_url(@update.profile), notice: 'Update was successfully updated.' }
        format.json { render :show, status: :ok, location: @update }
      else
        format.html { render :edit }
        format.json { render json: @update.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /updates/1
  # DELETE /updates/1.json
  def destroy
    @update.destroy
    respond_to do |format|
      format.html { redirect_to profile_updates_url(@update.profile), notice: 'Update was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_update
      @update = Update.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def update_params
      params.require(:update).permit(:weight, :notes)
    end
end

myFitWeb/app/helpers/updates_helper.rb
module UpdatesHelper
end

myFitWeb/app/views/updates/_form.html.erb
<%= form_for([@profile, @update]) do |f| %>
  <% if @update.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@update.errors.count, "error") %> prohibited this update from being saved:</h2>

      <ul>
      <% @update.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :weight %><br>
    <%= f.text_field :weight %>
  </div>
  <div class="field">
    <%= f.label :notes %><br>
    <%= f.text_area :notes %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

myFitWeb/app/views/updates/edit.html.erb
<div class="container">
<h1 class="header">Editing Update</h1>

<%= render 'form' %>

<%= link_to 'Back', profile_updates_path(@update.profile) %>
</div>

myFitWeb/app/views/updates/index.html.erb
<div class="container">
  <h1 id="update_header">Listing Your Updates</h1>
  <p>
    <% if @updates.empty? %>
        <small>You have not logged an update</small>
    <% else %>
      <table class="table">
        <thead>
          <tr>
            <th>Date Added</th>
            <th>Weight</th>
            <th>Notes</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @updates.each do |update| %>
            <tr>
                <td><%= update.created_at.to_formatted_s(:long_ordinal) %></td>
                <td><%= update.weight %></td>
                <td><%= update.notes %></td>
                <td><%= link_to 'Add Picture', update %></td>
                <td><%= link_to 'Edit', edit_update_path(update) %></td>
                <td><%= link_to 'Delete', update, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% end %>
  </p>
  <div class="update_content">
    <%= link_to 'New Update', new_profile_update_path(@profile) %>
  </div>
  <br><br>
  <hr>
  <h1 id="workout_header"> Listing Your Workouts </h1>
    <p>
      <% if @workouts.empty? %>
        <small>You have not created a workout</small>
      <% else %>
        <%= render :partial => 'workouts/workouts', :locals => { :workouts => @workouts } %>
      <% end %>
    </p>
    <div class="workout_content">
      <%= link_to 'New Workout', new_profile_workout_path(@profile)%>
    </div>
</div>

myFitWeb/app/views/updates/new.html.erb
<div class="container">

<h1 class=header>New Update</h1>

<%= render 'form' %>

<%= link_to 'Back', profile_updates_path(@profile)  %>
</div>

myFitWeb/app/views/updates/show.html.erb
<div class="container">
<div class="show_table">
<table class="table">
  <thead>
    <tr>
      <th>Weight</th>
      <th>Notes</th>
      <th>Date Added</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <td><%= @update.weight %></td>
    <td><%= @update.notes %></td>
    <td><%= @update.created_at.to_formatted_s(:long_ordinal) %></td>
  </tbody>
</table>
</div>
<p>
  <div class="picture_section">
  <% if !@update.pictures.empty? %>
    <% @update.pictures.each do |picture| %>
      <% if !picture.new_record? %>
        <div class="floating_box">
          <div class="pic"><%= image_tag picture.name, size: "175x200", alt: picture.name %></div>
        </div>
      <% end %>
    <% end %>
  <% end %>
  </div>
</p>
<div class="new_pic">
<h1 class="header"> Add a New Progress Picture </h1>
<%= render :partial => 'pictures/form', :locals => { :update => @update } %>

<%= link_to 'Back', profile_updates_path(@profile) %>
</div>
</div>