myFitWeb/config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: "users/registrations" }

  resources :users

  resources :profiles, shallow: true do
    resources :goals
    resources :supplements
    resources :updates, shallow: true do
      resources :pictures
    end
    resources :workouts, shallow: true do
      resources :exercises
    end
  end

  root 'home#index'

end

myFitWeb/app/models/profile.rb
class Profile < ActiveRecord::Base

  has_many :workouts, dependent: :destroy
  has_many :goals, dependent: :destroy
  has_many :supplements, dependent: :destroy
  has_many :updates, dependent: :destroy
  has_many :pictures, through: :updates

  belongs_to :user


  def height
     feet.to_s + " feet " + inches.to_s + " inches"
  end

  def fat_weight
    if self.weight != nil && self.body_fat != nil
      fat_weight = self.weight * (self.body_fat * 0.01)
    end
  end

  def lean_mass
    if self.weight != nil && self.body_fat != nil
      lean_mass = self.weight - self.fat_weight
    end
  end

end

myFitWeb/app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]

  # GET /profiles
  # GET /profiles.json
  def index
    @profiles = Profile.all
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
    @profile = Profile.find params[:id]
    @user = current_user
    @name = @user.name
    @email = @user.email
    @goals = @profile.goals
    @supplements = @profile.supplements

  end

  # GET /profiles/new
  def new
    @profile = Profile.new
  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = Profile.new(profile_params)

    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: 'Profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params.require(:profile).permit(:weight, :feet, :inches, :body_fat, :age, :gender, :location, :gym, :user_id)
    end
end

myFitWeb/app/helpers/profiles_helper.rb
module ProfilesHelper
end

myFitWeb/app/views/profiles/_form.html.erb
<%= form_for(@profile) do |f| %>
  <% if @profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
      <% @profile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :age %><br>
    <%= f.number_field :age %>
  </div>
  <div class="field">
    <%= f.label :gender %><br>
    <%= f.text_field :gender %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :gym %><br>
    <%= f.text_field :gym %>
  </div>
  <hr>
  <div class="field">
    <%= f.label :weight %><br>
    <%= f.text_field :weight %>
  </div>
  <div class="field">
    <%= f.label :body_fat %><br>
    <%= f.text_field :body_fat %>
  </div>
  <strong>Height:</strong>
  <br>
  <div class="field">
    <%= f.label :feet %><br>
    <%= f.number_field :feet %>
  </div>
  <div class="field">
    <%= f.label :inches %><br>
    <%= f.number_field :inches %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

myFitWeb/app/views/profiles/_weight_form.html.erb
<%= form_for(@profile) do |f| %>
  <% if @profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
      <% @profile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :weight %><br>
    <%= f.text_field :weight %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

myFitWeb/app/views/profiles/edit.html.erb
<div class="container">
  <h1 class="header">Editing Profile</h1>

  <%= render 'form' %>

  <%= link_to 'Back', profile_path %>
</div>

myFitWeb/app/views/profiles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Profiles</h1>

<table>
  <thead>
    <tr>
      <th>Weight</th>
      <th>Feet</th>
      <th>Inches</th>
      <th>Body fat</th>
      <th>Age</th>
      <th>Gender</th>
      <th>Location</th>
      <th>Gym</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @profiles.each do |profile| %>
      <tr>
        <td><%= profile.weight %></td>
        <td><%= profile.feet %></td>
        <td><%= profile.inches %></td>
        <td><%= profile.body_fat %></td>
        <td><%= profile.age %></td>
        <td><%= profile.gender %></td>
        <td><%= profile.location %></td>
        <td><%= profile.gym %></td>
        <td><%= profile.user_id %></td>
        <td><%= link_to 'Show', profile %></td>
        <td><%= link_to 'Edit', edit_profile_path(profile) %></td>
        <td><%= link_to 'Destroy', profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Profile', new_profile_path %>

myFitWeb/app/views/profiles/new.html.erb
<h1>New Profile</h1>

<%= render 'form' %>

<%= link_to 'Back', profiles_path %>

myFitWeb/app/views/profiles/show.html.erb
<style>
body {
  background-color: #F8F8F8;
}

.personal p {
  font-size: 16px;
  line-height: 1.5em;
}

.weight p {
  font-size: 16px;
  line-height: 1.5em;
}
</style>
<body>
  <div class="container">
    <div class="top_section">
      <div class="personal">
        <p>
          <span class="classifier"><strong>Name</strong></span>
          <span class="info"><%= @name %></span>
          <br>
        </p>
        <p>
          <span class="classifier"><strong>Email</strong></span>
          <span class="info"><%= @email %></span>
          <br>
        </p>

        <p>
          <span class="classifier"><strong>Age</strong></span>
          <% if @profile.age == nil %>
          <span class="info">--</span><br>
          <% else %>
          <span class="info"><%= @profile.age %></span><br>
          <% end %>
        </p>

        <p>
          <span class="classifier"><strong>Gender</strong></span>
          <% if @profile.gender == nil %>
          <span class="info">--</span><br>
          <% else %>
          <span class="info"><%= @profile.gender %></span><br>
          <% end %>
        </p>

        <p>
          <span class="classifier"><strong>Location</strong></span>
          <% if @profile.location == nil %>
          <span class="info">--</span><br>
          <% else %>
          <span class="info"><%= @profile.location %></span><br>
          <% end %>
        </p>

        <p>
          <span class="classifier"><strong>Gym</strong></span>
          <% if @profile.gym == nil %>
          <span class="info">--</span><br>
          <% else %>
          <span class="info"><%= @profile.gym %></span><br>
          <% end %>
          <div class="edit_button1">
            <small><%= link_to 'Edit', edit_profile_path(@profile) %></small>
          </div>
          <br>
        </p>
      </div>

      <div class="weight_title">
        <h1>Body Composition</h1>
      </div>
      <div class="weight">
        <p>
          <span class="weight_classifier"><strong>Current Weight</strong></span>
          <% if @profile.weight == nil %>
          <span class="weight_info">--</span><br>
          <% else %>
          <span class="weight_info"><%= @profile.weight %> <small>LBS.</small></span><br>
          <% end %>
        </p>

        <p>
          <span class="weight_classifier"><strong>Current Body Fat</strong></span>
          <% if @profile.body_fat == nil %>
          <span class="weight_info">--</span><br>
          <% else %>
          <span class="weight_info"><%= @profile.body_fat %> <small>%</small></span><br>
          <% end %>
        </p>
        <p>
        <% if @profile.lean_mass != nil && @profile.fat_weight != nil%>
          <span class="weight_classifier"><strong>Lean Body Mass</strong></span>
          <span class="weight_info"><%= @profile.lean_mass %> <small>LBS.</small></span><br>
          <span class="weight_classifier"><strong>Body Fat</strong></span>
          <span class="weight_info"><%= @profile.fat_weight %> <small>LBS.</small></span><br>
        <% end %>
        </p>

        <p>
          <span class="weight_classifier"><strong>Height</strong></span>
          <% if @profile.feet == nil %>
          <span class="weight_info">--</span><br>
          <% else %>
          <span class="weight_info"><%= @profile.height %></span><br>
          <% end %>
        </p>

        <div class="edit_button">
          <small><%= link_to 'Edit', edit_profile_path(@profile) %></small>
        </div>
      </div>
    </div>
    <div class="goals_title">
      <h1>Goals</h1>
    </div>
    <div class="goals">
      <div class="goals_content">
        <p>
          <% if @goals.empty? %>
          <small>You Have Not Set a Goal</small><br>
          <% else %>
          <table class="table">
            <thead>
              <tr>
                <th>Goal</th>
                <th>Description</th>
                <th colspan="3"></th>
              </tr>
            </thead>
            <tbody>
              <% @goals.each do |goal| %>
              <tr>
                <td><%= goal.name %></td>
                <td><%= goal.description %></td>
                <td><%= link_to 'Edit', edit_goal_path(goal) %></td>
                <td><%= link_to 'Delete', goal, method: :delete, data: { confirm: 'Are you sure?' } %></td>
              </tr>
              <% end %>
            </tbody>
          </table>
          <% end %>
          </p>
          <%= link_to "Add a Goal", new_profile_goal_path(@profile) %>

      </div>
    </div>

    <div class="supplements_title">
      <h1>Supplements</h1>
    </div>
    <div class="supplements">
      <div class="supplements_content">
        <p>
          <% if @supplements.empty? %>
          <small>You Have Not Added Any Supplements</small><br>
          <% else %>

            <table class="table">
              <thead>
                <tr>
                  <th>Supplement</th>
                  <th colspan="2"></th>
                </tr>
              </thead>
              <tbody>
                <% @supplements.each do |supplement| %>
                <tr>
                  <td><%= supplement.name %></td>
                  <td><%= link_to 'Edit', edit_supplement_path(supplement) %></td>
                  <td><%= link_to 'Delete', supplement, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                </tr>
                <% end %>
              </tbody>
              <% end %>
            </table>
        </p>
        <%= link_to "Add a Supplement", new_profile_supplement_path(@profile) %>
      </div>
    </div>
  </div>
</body>