myFitWeb/config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: "users/registrations" }

  resources :users

  resources :profiles, shallow: true do
    resources :goals
    resources :supplements
    resources :updates, shallow: true do
      resources :pictures
    end
    resources :workouts, shallow: true do
      resources :exercises
    end
  end

  root 'home#index'

end

myFitWeb/app/models/supplement.rb
class Supplement < ActiveRecord::Base

  belongs_to :profile

end

myFitWeb/app/controllers/supplements_controller.rb
class SupplementsController < ApplicationController
  before_action :set_supplement, only: [:show, :edit, :update, :destroy]

  # GET /supplements
  # GET /supplements.json
  def index
    @supplements = Supplement.all
  end

  # GET /supplements/1
  # GET /supplements/1.json
  def show
  end

  # GET /supplements/new
  def new
    @profile = Profile.find params[:profile_id]
    @supplement = @profile.supplements.new
  end

  # GET /supplements/1/edit
  def edit
  end

  # POST /supplements
  # POST /supplements.json
  def create
    @profile = Profile.find params[:profile_id]
    @supplement = @profile.supplements.new(supplement_params)

    respond_to do |format|
      if @supplement.save
        format.html { redirect_to profile_url(@profile), notice: 'Supplement was successfully created.' }
        format.json { render :show, status: :created, location: @supplement }
      else
        format.html { render :new }
        format.json { render json: @supplement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /supplements/1
  # PATCH/PUT /supplements/1.json
  def update
    respond_to do |format|
      if @supplement.update(supplement_params)
        format.html { redirect_to profile_url(@supplement.profile), notice: 'Supplement was successfully updated.' }
        format.json { render :show, status: :ok, location: @supplement }
      else
        format.html { render :edit }
        format.json { render json: @supplement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /supplements/1
  # DELETE /supplements/1.json
  def destroy
    @supplement.destroy
    respond_to do |format|
      format.html { redirect_to profile_url(@supplement.profile), notice: 'Supplement was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_supplement
      @supplement = Supplement.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def supplement_params
      params.require(:supplement).permit(:name, :profile_id)
    end
end

myFitWeb/app/helpers/supplements_helper.rb
module SupplementsHelper
end

myFitWeb/app/views/supplements/_form.html.erb
<%= form_for([@profile, @supplement]) do |f| %>
  <% if @supplement.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@supplement.errors.count, "error") %> prohibited this supplement from being saved:</h2>

      <ul>
      <% @supplement.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

myFitWeb/app/views/supplements/edit.html.erb
<div class="container">
<h1 class="header">Editing Supplement</h1>

<%= render 'form' %>

<%= link_to 'Show', @supplement %> |
<%= link_to 'Back', profile_path(@supplement.profile) %>
</div>

myFitWeb/app/views/supplements/index.html.erb
<h1>Listing Supplements</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Profile</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @supplements.each do |supplement| %>
      <tr>
        <td><%= supplement.name %></td>
        <td><%= supplement.profile_id %></td>
        <td><%= link_to 'Show', supplement %></td>
        <td><%= link_to 'Edit', edit_supplement_path(supplement) %></td>
        <td><%= link_to 'Delete', supplement, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Supplement', new_supplement_path %>

myFitWeb/app/views/supplements/new.html.erb
<div class="container">
<h1 class="header">New Supplement</h1>

<%= render 'form' %>

<%= link_to 'Back', profile_path(@profile) %>
</div>

myFitWeb/app/views/supplements/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @supplement.name %>
</p>

<p>
  <strong>Profile:</strong>
  <%= @supplement.profile_id %>
</p>

<%= link_to 'Edit', edit_supplement_path(@supplement) %> |
<%= link_to 'Back', supplements_path %>